name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up SDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16.0.2'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
    - name: Update TIMESTAMP on .env.example
      run:  sed -i -e
            "s/TIMESTAMP=.*/TIMESTAMP=${{ secrets.TIMESTAMP }}/g"
            .env.example
    - name: Update PUBLIC_KEY on .env.example
      run:  sed -i -e
            "s/PUBLIC_KEY=.*/PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}/g"
            .env.example
    - name: Update HASH on .env.example
      run:  sed -i -e
            "s/HASH=.*/HASH=${{ secrets.HASH }}/g"
            .env.example
    - name: Set up environment variables
      run: |
        cp .env.example .env
        sed -i "s/TIMESTAMP/${{ secrets.TIMESTAMP }}/g" .env
        sed -i "s/PUBLIC_KEY/${{ secrets.PUBLIC_KEY }}/g" .env
        sed -i "s/HASH/${{ secrets.HASH }}/g" .env
    - name: Run tests
      run: |
        mvn test -Dtest=GetAllCharacters
        mvn test -Dtest=GetCharactersPerComic
        mvn test -Dtest=GetComicsPerCharacter
