name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up SDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16.0.2'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
    - name: Set up environment variables
      run: cp .env.example .env
      env:
       TIMESTAMP: ${{ secrets.TIMESTAMP }}
       PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
       HASH: ${{ secrets.HASH }}
    - name: Run tests
      run: |
        mvn test -Dtest=GetAllCharacters
        mvn test -Dtest=GetCharactersPerComic
        mvn test -Dtest=GetComicsPerCharacter
